[workspace]
resolver = "3"
members = [ "pacs/efr32fg23", "xtask"]

[workspace.package]
keywords = ["no-std", "cortex-m", "efr32"]
edition = "2024"
version = "0.1.0"
readme = "readme.md"

[workspace.dependencies]
cortex-m = "0.7.3"
vcell = "0.1.3"
cortex-m-rt = "0.7.5"
